/**
 * Transpiler Output Types
 * 
 * Type definitions for Home Assistant automation and script structures
 * generated by the ST transpiler.
 */

// HelperConfig is imported from analyzer/types

// ============================================================================
// HA Automation/Script Types
// ============================================================================

export interface HAAutomation {
  id: string;
  alias: string;
  description?: string;
  mode: 'single' | 'restart' | 'queued' | 'parallel';
  max?: number;
  trigger: HATrigger[];
  condition?: HACondition[];
  action: HAAction[];
  variables?: Record<string, string>;
}

export interface HAScript {
  alias: string;
  description?: string;
  mode: 'single' | 'restart' | 'queued' | 'parallel';
  max?: number;
  sequence: HAAction[];
  variables?: Record<string, string>;
  fields?: Record<string, HAScriptField>;
}

export interface HAScriptField {
  name: string;
  description?: string;
  required?: boolean;
  default?: unknown;
  selector?: Record<string, unknown>;
}

// ============================================================================
// Trigger Types
// ============================================================================

export type HATrigger = 
  | HAStateTrigger
  | HAEventTrigger
  | HATimeTrigger
  | HANumericStateTrigger;

export interface HAStateTrigger {
  platform: 'state';
  entity_id: string | string[];
  from?: string | string[];
  to?: string | string[];
  not_from?: string[];
  not_to?: string[];
  attribute?: string;
  for?: string | HADuration;
  id?: string;
}

export interface HAEventTrigger {
  platform: 'event';
  event_type: string;
  event_data?: Record<string, unknown>;
  id?: string;
}

export interface HATimeTrigger {
  platform: 'time';
  at: string;
  id?: string;
}

export interface HANumericStateTrigger {
  platform: 'numeric_state';
  entity_id: string | string[];
  above?: number | string;
  below?: number | string;
  attribute?: string;
  for?: string | HADuration;
  id?: string;
}

export interface HADuration {
  hours?: number;
  minutes?: number;
  seconds?: number;
  milliseconds?: number;
}

// ============================================================================
// Condition Types
// ============================================================================

export type HACondition =
  | HAStateCondition
  | HANumericStateCondition
  | HATemplateCondition
  | HAAndCondition
  | HAOrCondition
  | HANotCondition;

export interface HAStateCondition {
  condition: 'state';
  entity_id: string;
  state: string | string[];
  attribute?: string;
}

export interface HANumericStateCondition {
  condition: 'numeric_state';
  entity_id: string;
  above?: number | string;
  below?: number | string;
  attribute?: string;
}

export interface HATemplateCondition {
  condition: 'template';
  value_template: string;
}

export interface HAAndCondition {
  condition: 'and';
  conditions: HACondition[];
}

export interface HAOrCondition {
  condition: 'or';
  conditions: HACondition[];
}

export interface HANotCondition {
  condition: 'not';
  conditions: HACondition[];
}

// ============================================================================
// Action Types
// ============================================================================

export type HAAction =
  | HAServiceAction
  | HADelayAction
  | HAWaitAction
  | HAChooseAction
  | HARepeatAction
  | HAIfAction
  | HAVariablesAction
  | HAStopAction
  | HAEventAction;

export interface HAServiceAction {
  service: string;
  target?: HATarget;
  data?: Record<string, unknown>;
  data_template?: Record<string, string>;
}

export interface HATarget {
  entity_id?: string | string[];
  device_id?: string | string[];
  area_id?: string | string[];
}

export interface HADelayAction {
  delay: string | HADuration;
}

export interface HAWaitAction {
  wait_template: string;
  timeout?: string | HADuration;
  continue_on_timeout?: boolean;
}

export interface HAChooseAction {
  choose: HAChooseOption[];
  default?: HAAction[];
}

export interface HAChooseOption {
  conditions: HACondition[];
  sequence: HAAction[];
}

export interface HARepeatAction {
  repeat: HARepeatConfig;
}

export interface HARepeatConfig {
  count?: number | string;
  while?: HACondition[];
  until?: HACondition[];
  sequence: HAAction[];
}

export interface HAIfAction {
  if: HACondition[];
  then: HAAction[];
  else?: HAAction[];
}

export interface HAVariablesAction {
  variables: Record<string, string | number | boolean>;
}

export interface HAStopAction {
  stop: string;
  error?: boolean;
}

export interface HAEventAction {
  event: string;
  event_data?: Record<string, unknown>;
  event_data_template?: Record<string, string>;
}

// ============================================================================
// Transpiler Result
// ============================================================================

export interface TranspilerResult {
  automation: HAAutomation;
  script: HAScript;
  helpers: import("../analyzer/types").HelperConfig[];
  /**
   * Additional automations generated by the transpiler
   * (e.g. timer.finished handlers for TON/TOF/TP)
   */
  additionalAutomations?: HAAutomation[];
  sourceMap: SourceMap;
  diagnostics: TranspilerDiagnostic[];
}

// SourceMap types are now imported from sourcemap module
import type { SourceMap } from '../sourcemap/source-map-types';
export type { SourceMap };

export interface TranspilerDiagnostic {
  severity: 'Error' | 'Warning' | 'Info';
  code: string;
  message: string;
  stLine?: number;
}

// ============================================================================
// Context Types
// ============================================================================

export interface TranspilerContext {
  programName: string;
  projectName: string;
  variables: Map<string, VariableInfo>;
  entityBindings: Map<string, EntityInfo>;
  currentPath: string[];
  loopDepth: number;
  safetyCounters: number;
}

export interface VariableInfo {
  name: string;
  dataType: string;
  isInput: boolean;
  isOutput: boolean;
  isPersistent: boolean;
  helperId?: string;
  entityId?: string;
}

export interface EntityInfo {
  entityId: string;
  variableName: string;
  direction: 'INPUT' | 'OUTPUT';
  dataType: string;
}
